# Generated by Django 5.2.16 on 2026-07-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_id', models.CharField(db_index=True, max_length=64)),
                ('klasik_skor', models.IntegerField(blank=True, help_text='Banka skoru — DEĞİŞTİRİLMEDİ', null=True)),
                ('aks_skor', models.IntegerField(help_text='AKS tamamlayıcı skor')),
                ('karar', models.CharField(max_length=128)),
                ('onerilen_limit', models.IntegerField(blank=True, null=True)),
                ('politika_notu', models.CharField(default='AKS tamamlayıcıdır; banka segmenti/skoru değiştirilmedi.', max_length=200)),
                ('ajanlar', models.JSONField(default=list)),
                ('kaynak', models.CharField(default='api', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Denetim Kaydı',
                'verbose_name_plural': 'Denetim İzi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('persona', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Müşteri',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_id', models.CharField(db_index=True, max_length=64)),
                ('klasik_skor', models.IntegerField(blank=True, null=True)),
                ('aks_skor', models.IntegerField()),
                ('risk_seviyesi', models.CharField(max_length=32)),
                ('karar', models.CharField(max_length=128)),
                ('onerilen_limit', models.IntegerField(blank=True, null=True)),
                ('ozellikler', models.JSONField(default=dict)),
                ('kaynak', models.CharField(default='api', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='audit.customer')),
            ],
            options={
                'verbose_name': 'Değerlendirme',
                'ordering': ['-created_at'],
            },
        ),
    ]
