# Generated by Django 5.2.16 on 2026-07-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='kapasite_sinyali',
            field=models.IntegerField(blank=True, help_text='0-100, 50=nötr', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pd_fark',
            field=models.FloatField(blank=True, help_text='pd_geleneksel_bant − pd_davranissal', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='kapasite_sinyali',
            field=models.IntegerField(blank=True, help_text='0-100, 50=nötr', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='pd_fark',
            field=models.FloatField(blank=True, help_text='pd_geleneksel_bant − pd_davranissal', null=True),
        ),
    ]
