# Generated by Django 5.2.16 on 2026-07-26 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_assessment_user'),
        ('kimlik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='belge_parmak_izi',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='assessment',
            name='kaynak_format',
            field=models.CharField(blank=True, default='', help_text='csv/xlsx/pdf', max_length=16),
        ),
        migrations.AddField(
            model_name='assessment',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degerlendirmeler', to='kimlik.profil'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='sahiplik_bayraklari',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='sahiplik_beyani',
            field=models.BooleanField(default=False, help_text="Yükleyen 'bu ekstre bana ait' onayı verdi mi"),
        ),
    ]
