# Generated by Django 5.2.16 on 2026-07-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_assessment_belge_parmak_izi_assessment_kaynak_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='yukleme_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
