# Generated by Django 5.2.16 on 2026-07-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_assessment_yukleme_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='ham_islemler',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
