/** @type {import('tailwindcss').Config} */
// Design tokens ported 1:1 from product/03-frontend/stitch-output/synthetic_intelligence_interface/DESIGN.md
// (the Google Stitch "AKS Intelligence" design system) so every page matches the approved mockups.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#39393b",
        tertiary: "#d0bcff",
        primary: "#c3c0ff",
        "primary-container": "#4f46e5",
        "secondary-container": "#00a2e6",
        "on-tertiary-fixed": "#23005c",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-container": "#6f3dd9",
        "on-secondary": "#00344d",
        "on-background": "#e5e1e4",
        "on-surface-variant": "#c7c4d8",
        "on-primary-container": "#dad7ff",
        "surface-tint": "#c3c0ff",
        "on-tertiary": "#3c0091",
        background: "#020617",
        "surface-dim": "#131315",
        "surface-container-high": "#2a2a2c",
        "on-error-container": "#ffdad6",
        "surface-container": "#201f22",
        "tertiary-fixed": "#e9ddff",
        "inverse-on-surface": "#313032",
        "on-tertiary-fixed-variant": "#5516be",
        "secondary-fixed": "#c9e6ff",
        "on-secondary-container": "#00344e",
        "surface-variant": "#353437",
        "inverse-primary": "#4d44e3",
        error: "#ffb4ab",
        "outline-variant": "#464555",
        "on-secondary-fixed-variant": "#004c6e",
        "on-primary": "#1d00a5",
        "primary-fixed": "#e2dfff",
        "tertiary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#001e2f",
        surface: "#131315",
        "on-surface": "#e5e1e4",
        "error-container": "#93000a",
        "inverse-surface": "#e5e1e4",
        "on-error": "#690005",
        secondary: "#89ceff",
        outline: "#918fa1",
        "on-tertiary-container": "#e3d5ff",
        "on-primary-fixed": "#0f0069",
        "surface-container-highest": "#353437",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1c1b1d",
        "secondary-fixed-dim": "#89ceff",
        "on-primary-fixed-variant": "#3323cc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "24px",
        "stack-md": "16px",
        "stack-sm": "8px",
        unit: "4px",
        "stack-lg": "32px",
        gutter: "16px",
      },
      fontFamily: {
        "body-sm": ["Geist", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "display-lg": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-sm": ["Geist", "sans-serif"],
        "display-sm-mobile": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-sm": ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-sm-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
