# Generated by Django 5.2.16 on 2026-07-26 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=128)),
                ('kod', models.SlugField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurum',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aks_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('telefon_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('telefon_dogrulandi_mi', models.BooleanField(default=False)),
                ('telefon_dogrulandi_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profiller',
            },
        ),
        migrations.CreateModel(
            name='ErisimTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amac', models.CharField(max_length=200)),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('iptal_edildi', 'İptal Edildi')], default='bekliyor', max_length=16)),
                ('gecerlilik_bitis', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karar_at', models.DateTimeField(blank=True, null=True)),
                ('talep_eden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erisim_talepleri', to='kimlik.kurum')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erisim_talepleri', to='kimlik.profil')),
            ],
            options={
                'verbose_name': 'Erişim Talebi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RizaKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olay', models.CharField(choices=[('talep_olusturuldu', 'Talep Oluşturuldu'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('iptal_edildi', 'İptal Edildi'), ('erisim_kullanildi', 'Erişim Kullanıldı')], max_length=24)),
                ('aks_no', models.CharField(db_index=True, max_length=20)),
                ('kurum_kod', models.CharField(db_index=True, max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('erisim_talebi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riza_kayitlari', to='kimlik.erisimtalebi')),
            ],
            options={
                'verbose_name': 'Rıza Kaydı',
                'verbose_name_plural': 'Rıza Defteri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelefonDogrulama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon_hash', models.CharField(max_length=64)),
                ('kod_hash', models.CharField(max_length=64)),
                ('son_gecerlilik', models.DateTimeField()),
                ('deneme_sayisi', models.IntegerField(default=0)),
                ('kullanildi_mi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefon_dogrulamalari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telefon Doğrulama',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KurumUyeligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('uye', 'Üye'), ('yonetici', 'Yönetici')], default='uye', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyeler', to='kimlik.kurum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurum_uyelikleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kurum Üyeliği',
                'unique_together': {('user', 'kurum')},
            },
        ),
    ]
